### ISSUE TITLE
scalar_conservation module: Bad string input with CMake tests

### ISSUE THREAD

**Issue by ejtovar** [conservation-laws/ryujin#20]
The following tests:

`tests/scalar_conservation/hyperbolic_system.cc` and `tests/scalar_conservation/riemann_solver.cc` 

are seg faulting in debug mode seemingly due to a bad string input. Here is the output of `ctest --output-on-failure -R scalar_conservation/hyperbolic_system.debug`:

```bash
Test project /Users/ericjtovar/Software/ryujin/build
    Start 47: scalar_conservation/hyperbolic_system.debug
1/1 Test #47: scalar_conservation/hyperbolic_system.debug ...***Failed    7.08 sec
Test scalar_conservation/hyperbolic_system.debug: RUN
===============================   OUTPUT BEGIN  ===============================
[0/2] Re-checking globbed directories...
[1/5] Building CXX object tests/scalar_conservation/CMakeFiles/scalar_conservation.hyperbolic_system.debug.dir/hyperbolic_system.cc.o
[2/5] Linking CXX executable tests/scalar_conservation/hyperbolic_system.debug/hyperbolic_system.debug
[3/5] Generating hyperbolic_system.debug/output
FAILED: tests/scalar_conservation/hyperbolic_system.debug/output /Users/ericjtovar/Software/ryujin/build/tests/scalar_conservation/hyperbolic_system.debug/output
cd /Users/ericjtovar/Software/ryujin/build/tests/scalar_conservation/hyperbolic_system.debug && /bin/bash /Users/ericjtovar/Software/dealii-install/share/deal.II/scripts/run_test.sh run scalar_conservation/hyperbolic_system.debug TEST_N_THREADS=0 /Users/ericjtovar/Software/ryujin/build/tests/scalar_conservation/hyperbolic_system.debug/hyperbolic_system.debug && /usr/bin/perl -pi /Users/ericjtovar/Software/dealii-install/share/deal.II/scripts/normalize.pl /Users/ericjtovar/Software/ryujin/build/tests/scalar_conservation/hyperbolic_system.debug/output
/Users/ericjtovar/Software/dealii-install/share/deal.II/scripts/run_test.sh: line 35: 17052 Abort trap: 6           "$@" > stdout 2>&1
scalar_conservation/hyperbolic_system.debug: BUILD successful.
scalar_conservation/hyperbolic_system.debug: RUN failed. ------ Return code 134
scalar_conservation/hyperbolic_system.debug: RUN failed. ------ Result: /Users/ericjtovar/Software/ryujin/build/tests/scalar_conservation/hyperbolic_system.debug/failing_output
scalar_conservation/hyperbolic_system.debug: RUN failed. ------ Partial output:
dim = 1
f(u)={burgers}
state = 1.4000000000e+00
square_entropy = 9.8000000000e-01
square_entropy_derivative = 1.4000000000e+00
flux = 9.8000000000e-01
flux_gradient = 1.4000000000e+00

=================================================================
==17076==ERROR: AddressSanitizer: stack-use-after-return on address 0x000118f09647 at pc 0x000104e11a34 bp 0x00016affd260 sp 0x00016affd258
READ of size 1 at 0x000118f09647 thread T0
    #0 0x104e11a30 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const string:1459
    #1 0x104e311a4 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__move_assign(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::integral_constant<bool, true>) string:2498
    #2 0x104e30f94 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) string:2520
    #3 0x104e308c8 in void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const parameter_handler.h:2358
    #4 0x104e30720 in decltype(static_cast<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >>(fp)(static_cast<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(fp0))) std::__1::__invoke<void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) type_traits:3918
    #5 0x104e30658 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) invoke.h:61
    #6 0x104e305ec in std::__1::__function::__alloc_func<void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) function.h:178
    #7 0x104e2d768 in std::__1::__function::__func<void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&), std::__1::allocator<void dealii::ParameterHandler::add_parameter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dealii::Patterns::PatternBase const&, bool)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) function.h:352
    #8 0x13966d460 in std::__1::__function::__value_func<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const function.h:505
    #9 0x13964f638 in std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const function.h:1182
    #10 0x139656284 in dealii::ParameterHandler::scan_line(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, bool) parameter_handler.cc:1981
    #11 0x13964ca30 in dealii::ParameterHandler::parse_input(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)::$_0::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int) const parameter_handler.cc:468
    #12 0x13964c504 in dealii::ParameterHandler::parse_input(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) parameter_handler.cc:520
    #13 0x1396736d0 in dealii::ParameterAcceptor::initialize(std::__1::basic_istream<char, std::__1::char_traits<char> >&, dealii::ParameterHandler&) parameter_acceptor.cc:122
    #14 0x1064d86c0 in void test<2, double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) hyperbolic_system.cc:27
    #15 0x1064d6be8 in main hyperbolic_system.cc:52
    #16 0x109dc5088 in start+0x204 (dyld:arm64e+0x5088)

Address 0x000118f09647 is located in stack of thread T0 at offset 1607 in frame
    #0 0x1064d6d00 in void test<1, double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) hyperbolic_system.cc:14

  This frame has 27 object(s):
    [32, 36) 'i.addr.i.i.i332'
    [48, 52) 'ref.tmp.i.i.i333'
    [64, 360) 'agg.tmp.i.i.i334'
    [432, 436) 'ref.tmp5.i.i.i335'
    [448, 452) 'ref.tmp8.i.i.i336'
    [464, 472) 'retval.i337'
    [496, 500) 'i.addr.i.i.i'
    [512, 516) 'ref.tmp.i.i.i'
    [528, 824) 'agg.tmp.i.i.i'
    [896, 900) 'ref.tmp5.i.i.i'
    [912, 916) 'ref.tmp8.i.i.i'
    [928, 936) 'retval.i'
    [960, 964) 'i.addr.i.i'
    [976, 980) 'ref.tmp.i.i'
    [992, 1288) 'agg.tmp.i.i'
    [1360, 1364) 'ref.tmp8.i.i'
    [1376, 1380) 'ref.tmp11.i.i'
    [1392, 1396) 'ref.tmp' (line 15)
    [1408, 1656) 'hyperbolic_system' (line 18) <== Memory access at offset 1607 is inside this variable
    [1728, 1752) 'ref.tmp8' (line 18)
    [1792, 1800) 'view' (line 19)
    [1824, 2104) 'parameters' (line 22)
    [2176, 2184) 'U' (line 33)
    [2208, 2232) 'ref.tmp108' (line 36)
    [2272, 2296) 'ref.tmp109' (line 36)
    [2336, 2344) 'ref.tmp229' (line 43)
    [2368, 2376) 'ref.tmp257' (line 44)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-return string:1459 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const
Shadow bytes around the buggy address:
  0x007023201270: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x007023201280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x007023201290: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0070232012a0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0070232012b0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x0070232012c0: f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5
  0x0070232012d0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0070232012e0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0070232012f0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x007023201300: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x007023201310: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17076==ABORTING
ninja: build stopped: subcommand failed.


scalar_conservation/hyperbolic_system.debug: ******    RUN failed    *******

===============================    OUTPUT END   ===============================
Expected stage PASSED - aborting
CMake Error at /Users/ericjtovar/Software/dealii-install/share/deal.II/scripts/run_test.cmake:116 (message):
  *** abort




0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.29 sec

The following tests FAILED:

```

**Comment by tamiko** [comment]
Yup. I was able to reproduce on a Mac an hour ago. I have fixed this in the pull request!

Thanks for investigating :smiley:
